version: '3.8'

services:
  spring-user-service:
    container_name: spring-user-container
    build: 
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Xmx512m"
    depends_on:
      - mysql-db
    networks:
      - spring-user-service-mysql-network

  mysql-db:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user-service-db
    volumes:
      - mysql-data:/var/lib/mysql
      - ./user.sql:/docker-entrypoint-initdb.d/user.sql
      # - ./user-service.sql:/docker-entrypoint-initdb.d/user-service.sql
    ports:
      - "3306:3306"
    networks:
      - spring-user-service-mysql-network

volumes:
  mysql-data:
networks:
  spring-user-service-mysql-network:
    driver: bridge
    name: service-mysql-network
