version: '3.8'

services:
  spring-user-service:
    container_name: spring-user-container
    build: 
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Xmx512m"
  
